### ISSUE TITLE
Peer Review :  Missing .tex file for VnV Plan

### ISSUE THREAD

**Issue by nivethakuruparan** [PaisWillie/Digital-Composite#57]
**Artifact Under Review**
.tex file

**Team Number for Team Doing the Review**
Team 4

**Description of Issue**
You are missing the .tex file for the VnV Plan. Make sure to add that in.

**Comment by PaisWillie** [comment]
A LaTeX document is not required. Our VnV plan was written plain text, so there is no `.tex` document.
