### ISSUE TITLE
Mandated Constraints

### ISSUE THREAD

**Issue by WajdanF** [PaisWillie/Digital-Composite#6]

**Comment by ZahinH** [comment]
Completed the following:
**Mandated Constraints**	
Solution Constraints	vii
Implementation Environment of the Current System	vii
Partner or Collaborative Applications	vii
Off-the-Shelf Software	vii
Anticipated Workplace Environment	vii
Schedule Constraints	vii
Budget Constraints	vii
Enterprise Constraints	viii
